# Makefile -- created by Will Sussman on November 22, 2019

ARDUINO_DIR = /usr/share/arduino
# ARDUINO_PORT = /dev/ttyACM*

USER_LIB_PATH = /home/riz3/willsLibrary/new/arduino/libraries
BOARD_TAG = uno

include ${ARDUINO_DIR}/Arduino.mk
